apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: group5
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: group5-app:1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
              name: http
          envFrom:
            - configMapRef:
                name: group5-config
          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: group5-secret
                  key: DB_PASSWORD
          readinessProbe:
            httpGet:
              path: /ready
              port: 5000
            initialDelaySeconds: 3
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 6
          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
