apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: group5
data:
  nginx.conf: |
    events {}

    http {
        upstream flask_backend {
            server backend:5000;
        }

        server {
            listen 80;

            location / {
                proxy_pass http://flask_backend;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
            }
        }
    }
