apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: group5
spec:
  selector:
    app: nginx
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30083
  type: NodePort
